/**
 * Auto-generated class for translation keys.
 * Generated from: C:\Users\DELL\Desktop\node\auth-pro-nest\src\i18n\en\translations.json
 * Do not edit this file directly. Regenerate it if needed.
 */
export class TranslationKeys {
  static email_invalid = 'translations.email_invalid';
  static email_too_long = 'translations.email_too_long';
  static email_not_string = 'translations.email_not_string';
  static email_required = 'translations.email_required';
  static username_invalid_characters = 'translations.username_invalid_characters';
  static username_length = 'translations.username_length';
  static username_not_string = 'translations.username_not_string';
  static username_required = 'translations.username_required';
  static password_weak = 'translations.password_weak';
  static password_required = 'translations.password_required';
  static password_not_string = 'translations.password_not_string';
  static code6_length = 'translations.code6_length';
  static code6_not_numeric = 'translations.code6_not_numeric';
  static fullname_length = 'translations.fullname_length';
  static fullname_not_string = 'translations.fullname_not_string';
  static confirm_password_required = 'translations.confirm_password_required';
  static passwords_not_match = 'translations.passwords_not_match';
  static roles_exclusion_message = 'translations.roles_exclusion_message';
  static roles_no_exclusion_allowed = 'translations.roles_no_exclusion_allowed';
  static roles_invalid_values = 'translations.roles_invalid_values';
  static roles_min_size = 'translations.roles_min_size';
  static roles_not_array = 'translations.roles_not_array';
}